apiVersion: batch/v1
kind: Job
metadata:
  name: flohmarkt-init
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: flohmarkt:1.0.0
          command: ["flohmarkt", "initdb"]
          envFrom:
            - configMapRef:
                name: flohmarkt-env
            - secretRef:
                name: flohmarkt-secrets
          volumeMounts:
            - name: flohmarkt-data
              mountPath: /var/lib/flohmarkt
      volumes:
        - name: flohmarkt-data
          persistentVolumeClaim:
            claimName: flohmarkt-data
