apiVersion: batch/v1
kind: Job
metadata:
  name: flohmarkt-init
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: harbor.obmondo.com/obmondo/flohmarkt:1.0.0
          args: ["initdb"]              # ← THIS is the key fix
          envFrom:
            - configMapRef:
                name: flohmarkt-env
            - secretRef:
                name: flohmarkt-secrets
          volumeMounts:
            - name: flohmarkt-data
              mountPath: /var/lib/flohmarkt
      volumes:
        - name: flohmarkt-data
          persistentVolumeClaim:
            claimName: flohmarkt-data
