apiVersion: v1
kind: Secret
metadata:
  name: flohmarkt-secrets
type: Opaque
stringData:
  FLOHMARKT_DB_USER: admin
  FLOHMARKT_DB_PASSWORD: supersecret

---
apiVersion: v1
kind: Secret
metadata:
  name: flohmarkt-db
type: Opaque
stringData:
  user: admin
  password: supersecret


