apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb
spec:
  serviceName: couchdb
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
        - name: couchdb
          image: couchdb:3.3
          ports:
            - containerPort: 5984
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: flohmarkt-db
                  key: user
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flohmarkt-db
                  key: password
          volumeMounts:
            - name: couchdb-data
              mountPath: /opt/couchdb/data
          readinessProbe:
            httpGet:
              path: /
              port: 5984
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: couchdb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
