apiVersion: v1
kind: Service
metadata:
  name: flohmarkt
spec:
  selector:
    app: flohmarkt
  ports:
    - port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
spec:
  ports:
    - port: 5984
      targetPort: 5984
  selector:
    app: couchdb

