apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mobilizon.fullname" . }}-uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
