image:
  repository: docker.io/library/matomo
  tag: 5.14.0-apache
  pullPolicy: IfNotPresent

host: matomo.example.com
extraHosts: [] # @schema item: string

ingress:
  className: ""
  annotations: {}
  tls: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 1Gi

persistence:
  size: 1Gi
  storageClassName: ""
  accessMode: ReadWriteMany # @schema enum: [ReadWriteOnce, ReadWriteMany]

archive:
  schedule: "*/5 * * * *"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi

plugins: [] # @schema item: object; itemRequired: [name, version]

oidc:
  enabled: false
  existingSecret: matomo-oidc
  keycloakUrl: ""
  realm: ""

#  This are configs for external mariadb deployment
mariadb:
  enabled: true
  rootPasswordSecretKeyRef: #cannot remove this when using zfs-localpv, the pod remains in pending state due to pvc issue
    name: matomo-secrets
    key: MARIADB_ROOT_PASSWORD
    generate: true
  storage:
    size: 1Gi
    storageClassName: ""
    resizeInUseVolumes: true
    waitForVolumeResize: true
  image: "mariadb:latest"
  imagePullPolicy: IfNotPresent
  imagePullSecrets: [] # @schema item: object
  username: matomo
  passwordSecretKeyRef:
    name: matomo-user
    key: db-password
    generate: true
  database: matomo-mariadb
  logicalbackup:
    enabled: false
    failedJobsHistoryLimit: 3
