apiVersion: v1
kind: Pod
metadata:
  name: index-docker-io-pod
  namespace: default
spec:
  containers:
  - name: nginx
    image: harbor.example.com/docker-hub-proxy-cache/library/nginx:latest
  imagePullSecrets:
  - name: harbor-proxy-cache
