apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.traefik.instanceLabelOverride | default "traefik" }}-middleware-config
  namespace: {{ $.Release.Namespace }}
data:
  config.yaml: |
    http:
      middlewares:
        ip-allow-list:
          ipAllowList:
            sourceRange:
            {{- range .Values.middleware.ipAllowList.sourceRanges }}
              - {{ . }}
            {{- end }}
