{{- if .Values.config.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openbao.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  {{- include "openbao.config.labels" . | nindent 2 }}
  {{- with .Values.config.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.config.serviceAccount.automountServiceAccountToken }}
{{- end }}
