harborProxyCache:
  enabled: false

kyverno:
  admissionController:
    container:
      # Default 10s is too short once this policy has many namespace overrides. 30s is the max allowed.
      extraArgs:
        webhookTimeout: "30"

resourceQuotaLimitRangeGenerator:
  enabled: true
  generateExisting: true
  defaultResourceQuotaRuleEnabled: true
  excludeNamespaces:
    resourceQuota: []
    limitRange: []

  defaults:
    resourceQuota:
      pods: "100"
      jobs: "100"

      # 100 cores per namespace is too much once a cluster has many namespaces.
      cpu:
        request: 250m

      memory:
        request: 0.5Gi
        limit: 400Gi

      storage:
        persistentVolumeClaims: null
        request: null

      ephemeralStorage:
        request: null
        limit: null

    limitRange:
      container:
        cpu:
          defaultRequest: 100m

        memory:
          defaultRequest: 128Mi
          default: 256Mi
          max: 4Gi

      pod:
        memory:
          max: 16Gi

      pvc:
        storage:
          max: 100Gi

  overrides:
    rook-ceph:
      limitRange:
        container: {}
