{
 "title": "App Suite / UI Middleware",
 "description": "node.js prometheus client basic metrics",
 "tags": [
  "nodejs",
  "ui"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(nodejs_version_info{service=~\".*-ui-middleware\"}, namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\",service=~\".*-ui-middleware\"}, service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\",service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}[1m]))",
     "legendFormat": "Requests per minute"
    }
   ]
  },
  {
   "title": "Errors (E): The number of failed requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5.*\",pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}[1m]))",
     "legendFormat": "Requests per minute"
    }
   ]
  },
  {
   "title": "Duration (D): The amount of time to process a request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (route,le) (rate(http_request_duration_seconds_bucket{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}[5m])))",
     "legendFormat": "p99 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (route,le) (rate(http_request_duration_seconds_bucket{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}[5m])))",
     "legendFormat": "Median {{route}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}[2m]) * 100",
     "legendFormat": "User CPU - {{pod}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{pod}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info{service=\"$service\", namespace=\"$namespace\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "Process Memory - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "Heap Total - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{pod=~\"$pod\"}",
     "legendFormat": "Heap Used - {{pod}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "External Memory - {{pod}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "Active Handler - {{pod}}"
    },
    {
     "expr": "nodejs_active_requests_total{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "Active Request - {{pod}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "Heap Total - {{pod}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "File cache size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_cache_size{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"} > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Version changes",
   "type": "stat",
   "description": "Version per pod active since",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(pod, version) (version_update_event{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}) * 1000",
     "legendFormat": "{{pod}} @ {{version}}"
    }
   ]
  },
  {
   "title": "Versions in Redis",
   "type": "stat",
   "description": "The number of unique versions in the Redis cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_version_count_gauge{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "Redis Versions"
    }
   ]
  },
  {
   "title": "Redis RAM Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(redis_used_ram{memory_type=\"usedMemoryRSSHuman\", namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "Maximum RSS"
    }
   ]
  },
  {
   "title": "Number of versions in S3",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(s3_version_count_gauge{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files in S3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "max(s3_total_number_of_files{namespace=\"$namespace\", service=\"$service\"}) by (service,version)",
     "legendFormat": "Version {{ version }} on {{ service }}"
    }
   ]
  }
 ]
}