{{- if and (not .Values.config.existingSecret) .Values.config.inline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "velociraptor.fullname" . }}-config
  labels:
    {{- include "velociraptor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.secretKey }}: |
    {{- .Values.config.inline | nindent 4 }}
{{- end }}
