apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "velociraptor.fullname" . }}
  labels:
    {{- include "velociraptor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "velociraptor.fullname" . }}-gui
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      {{- include "velociraptor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "velociraptor.configSecretName" . }}-{{ .Values.config.secretKey }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "velociraptor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: master
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "velociraptor.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- $init := include "velociraptor.overlayInitContainer" . }}
      {{- if trim $init }}
      initContainers:
        {{- $init | nindent 8 }}
      {{- end }}
      containers:
        - name: velociraptor
          image: {{ include "velociraptor.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config
            - {{ .Values.config.mountPath }}
            - frontend
            - -v
            {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: frontend
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
            - name: gui
              containerPort: {{ .Values.gui.containerPort }}
              protocol: TCP
            {{- if .Values.frontend.minions.enabled }}
            - name: api
              containerPort: {{ .Values.frontend.apiPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.serviceMonitor.enabled }}
            - name: metrics
              containerPort: {{ .Values.monitoring.containerPort }}
              protocol: TCP
            {{- end }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "velociraptor.configVolumeMount" . | nindent 12 }}
            {{- include "velociraptor.customArtifactsVolumeMount" . | nindent 12 }}
            - name: datastore
              mountPath: {{ .Values.persistence.mountPath }}
            {{- if .Values.tmpDir.enabled }}
            - name: tmp
              mountPath: /tmp
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- include "velociraptor.configVolumes" . | nindent 8 }}
        {{- include "velociraptor.customArtifactsVolume" . | nindent 8 }}
        {{- if .Values.tmpDir.enabled }}
        - name: tmp
          emptyDir:
            sizeLimit: {{ .Values.tmpDir.sizeLimit }}
        {{- end }}
        {{- if or (not .Values.persistence.enabled) .Values.persistence.existingClaim }}
        - name: datastore
          {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: datastore
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
  {{- end }}
