{{- if and .Values.webclients.rootFr.enabled .Values.webclients.rootFr.create.sessionSecret }}
{{- $fullName := printf "%s-rootfr" (include "stalwart-mail.fullname" .) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "stalwart-mail.labels" . | nindent 4 }}
    app.kubernetes.io/component: rootfr
data:
  {{- if .Values.webclients.rootFr.create.sessionSecret }}
  {{- $sessionSecret := "" }}
  {{- with (lookup "v1" "Secret" .Release.Namespace $fullName) }}
  {{- with get . "data" }}
  {{- $sessionSecret = (get . "session_secret" | b64dec) }}
  {{- end }}
  {{- else }}
  {{/* be the same then openssl rand -base64 32 */}}
  {{- $sessionSecret = randBytes 32 | b64enc }}
  {{- end }}
  "session_secret": {{ $sessionSecret | b64enc }}
  {{- end }}
{{- end }}
