apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dfir-iris.fullname" . }}-app
  labels:
    {{- include "dfir-iris.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.app.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "dfir-iris.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "dfir-iris.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["nohup", "./iris-entrypoint.sh", "iriswebapp"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{- include "dfir-iris.env" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 120
            periodSeconds: 30
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          volumeMounts:
            {{- include "dfir-iris.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "dfir-iris.volumes" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
