---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stalwart-mail.fullname" . }}
  labels:
    {{- include "stalwart-mail.labels" . | nindent 4 }}
    app.kubernetes.io/component: main
data:
  "config.json": |
    {{- .Values.config | toJson | nindent 4 }}
