{{- if and ((.Values.global).netpol).enabled ((.Values.global).sonarqube).netpol }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.global.netpol.releaseName | default .Release.Name }}-networkpolicy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: cilium-networkpolicy
spec:
  endpointSelector:
    matchLabels:
      {{- if .Values.global.sonarqube.endpointSelectorLabels }}
      {{- range $key, $value := .Values.global.sonarqube.endpointSelectorLabels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- else }}
      app: sonarqube
      {{- end }}
  ingress:
    # Allow same namespace traffic
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace | quote }}
    # traefik -> sonarqube
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Values.global.netpol.traefik.namespace | default "traefik" | quote }}
            app.kubernetes.io/name: traefik
      toPorts:
        - ports:
            - port: {{ .Values.global.sonarqube.servicePort | default "9000" | quote }}
              protocol: TCP
    # Sonar <-> Sonar
    - fromEndpoints:
        - matchLabels:
            {{- if .Values.global.sonarqube.endpointSelectorLabels }}
            {{- range $key, $value := .Values.global.sonarqube.endpointSelectorLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            {{- else }}
            app: sonarqube
            {{- end }}
  egress:
    # Sonar <-> Sonar
    - toEndpoints:
        - matchLabels:
            {{- if .Values.global.sonarqube.endpointSelectorLabels }}
            {{- range $key, $value := .Values.global.sonarqube.endpointSelectorLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            {{- else }}
            app: sonarqube
            {{- end }}
    # Sonar -> pgsql
    - toEndpoints:
        - matchLabels:
            cnpg.io/cluster: sonarqube-pgsql
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    # Sonar -> kube-apiserver
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "6443"
              protocol: TCP
    # Sonar -> DNS
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    # FQDNs
    - toFQDNs:
        - matchName: "repo1.maven.org"
        - matchName: "github.com"
        - matchName: "api.github.com"
        - matchName: "ghcr.io"
        - matchName: "charts.jetstack.io"
        - matchName: "release-assets.githubusercontent.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
{{- end }}