wazuh:
  dashboard:
    ingress:
      enabled: true
      className: traefik-internal
      tls: 
      - hosts:
        - wazuh.kam.obmondo.com                                                                                                                                                                                                                 
        secretName: wazuh-tls                                                                                                                                                                                                                   
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      host: wazuh.kam.obmondo.com

  indexer:
    replicas: 1
    storageSize: 5Gi

  agent:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi

  wazuh:
    master:
      storageSize: 5Gi
    worker:
      replicas: 1
      storageSize: 5Gi
